Print friendly error if cc is missing
If cc is not installed on the machine, we now get a friendlier error
message. Previously we got:

    user@host~$ dist/bin/actonc --version
    actonc: cc: readCreateProcess: posix_spawnp: does not exist (No such file or directory)
    user@host~$

And now we instead get:

    user@host~$ dist/bin/actonc --version
    ERROR: Unable to find cc (the C compiler)
    HINT: Ensure cc is in your PATH
    user@host~$