Use structured syntax errors
Rather than printing little text messages we now emit proper structured
errors for a number of errors we have in the parser, in particular for
string formatting. This allows us to add Notes and Hints, for example:

ERROR: [error Syntax error]: Expected digits after '.' in format specifier
     ╭──▶ test@1:38-1:38
     │
   1 │ f"Missing precision digits {value:10.}"
     •
     •                                      ╰╸ Expected digits after '.' in format specifier
     •
     │ Hint: Add precision digits, e.g. .2f for 2 decimal places
─────╯