Dedup stdout / stderr test output
Since we typically run many iterations of tests, we end up with a long
log of messages. Most of them are likely the same. We now dedup this
list, for example:

  stdout_capture:          FLAKY FAIL:  272 runs in 50.090ms
    testing.NotEqualError: Expected equal values but they are non-equal. A: 1 B: 2
    STDOUT:
      == 140 test runs with this output:
      Random number: 2

      == 132 test runs with this output:
      Random number: 1